---
changelog:
  enable: true
  git-log: true

uses:
  cargo:
    publish: true
    # tokens are loaded from ~/.cargo/config.toml
    registries:
      - crates.io
      - cscherr

api:
  github:
    type: github
    endpoint: https://github.com
    repository: autocrate
    auth:
      user: PlexSheep
      pass:
        env: TOKEN_GH
  cscherr:
    type: forgejo
    endpoint: https://git.cscherr.de
    repository: autocrate
    auth:
      user: PlexSheep
      pass:
        env: TOKEN_CSCHERR
