---
changelog:
  enable: true
  git-log: true

uses:
  cargo:
    publish: true
    # tokens are loaded from ~/.cargo/config.toml
    registries:
      - crates.io
      - cscherr

api:
  github:
    type: github
    endpoint: https://github.com
    auth:
      user: myUserName
      pass: token_superimportantsecret
  myserv:
    type: gitea
    endpoint: https://git.cscherr.de
    auth:
      user: myUserName
      pass: importantsecrettoken
